<?php

namespace AppBundle\Repository;

/**
 * CvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRepository extends \Doctrine\ORM\EntityRepository
{
}
