<?php

namespace AppBundle\Repository;

/**
 * EmployerPlacementAggreementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployerPlacementAggreementRepository extends \Doctrine\ORM\EntityRepository
{
}
