<?php

namespace AppBundle\Repository;

/**
 * EmployerRiskAssessmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployerRiskAssessmentRepository extends \Doctrine\ORM\EntityRepository
{
}
