<?php

namespace AppBundle\Repository;

/**
 * JobDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
