<?php

namespace AppBundle\Repository;

/**
 * LineManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
