<?php

namespace AppBundle\Repository;

/**
 * PlacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacementRepository extends \Doctrine\ORM\EntityRepository
{
}
